### Creating a resource
POST http://localhost:3000/books

Content-Type: application/json
{
    "title": "Data Engineer",
    "author": "Richard",
    "published_year": 2019
}
###
PUT http://localhost:3000/v1/books/16

Content-Type: application/json

{
    "title": "Programming with JavaScript",
    "author": "Richard",
    "published_year": 2020,
    "is_available": true
}


### Updating a resource
DELETE http://localhost:3000/v1/books/12

### get books by id
GET http://localhost:3000/v1/books/15